# Generated by Django 4.2.5 on 2023-10-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Select_city', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
                ('Mobile_no', models.IntegerField(max_length=10)),
                ('GSTNO', models.CharField(max_length=50)),
                ('Party_Type', models.CharField(max_length=50)),
                ('Address_full', models.CharField(max_length=200)),
            ],
        ),
    ]
