# Generated by Django 4.2.5 on 2023-10-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='Mobile_no',
        ),
    ]
