# Generated by Django 4.2.5 on 2023-10-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_remove_party_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='Landline_no',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='party',
            name='Mobile_no',
            field=models.IntegerField(default=True),
        ),
    ]
