# Generated by Django 4.2.5 on 2023-10-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_party_landline_no_party_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='Email',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
