# Generated by Django 4.2.5 on 2023-10-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_party_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
