# Generated by Django 4.2.5 on 2023-10-30 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_alter_party_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='Mobile_no',
            field=models.IntegerField(default=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
